### ISSUE TITLE
The opacity of other piles is not changed while temp depile in some examples

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#198]
In the matrix example, the opacity of other piles is not updated at all when a pile is temp depiling

![Apr-21-2020 13-08-23](https://user-images.githubusercontent.com/39853191/79827866-0cd6dc80-83d2-11ea-9198-db47ca7d1716.gif)

In the ridge plot example, the opacity of the piles which have more than 1 items is not correct

![Apr-21-2020 13-10-00](https://user-images.githubusercontent.com/39853191/79827977-4b6c9700-83d2-11ea-81ab-dd22a0914b34.gif)

The correct behavior should be like this

![Apr-21-2020 13-12-30](https://user-images.githubusercontent.com/39853191/79828013-5de6d080-83d2-11ea-8a6e-62788a73b47e.gif)

**Comment by flekschas** [comment]
The issue with the matrices is caused by the custom WebGL program that renders the matrices. This would be solved if we implement https://github.com/flekschas/piling.js/issues/204#issuecomment-623196046

The opacity issue with the scatterplots has never worked, unfortunately, but I found the issue 🎉As it turns out, the brightness filter causes the issue somehow. I have to find a way to properly multiply in the world alpha value.
